server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jrshelton/configServer
          searchPaths: solstice-ecommerce-cqrs-add_to_cart-command-handler, solstice-ecommerce-cqrs-add_to_cart-rest-api
          username: dummyaccounts
          password: temporarycontra1





